#!/usr/bin/env bash

browser() {
	local options=(
		"--app=http://localhost:$PORT/"
		'--kiosk'
		'--remote-debugging-port=9222'
	)

	pkill -f -- "$COMMAND_BROWSER"
	"$COMMAND_BROWSER" "${options[@]}" &
}

get_base_path() {
  [ -h "$0" ] && resolve_link "$0" || resolve_path "$0"
}

has_changes() {
	if shasum -c 'package-lock.shasum'; then
		return '0'
	fi

	shasum 'package-lock.json' > 'package-lock.shasum'

	return '1'
}

resolve_link() {
  resolve_path "$(readlink "$1")"
}

resolve_path() {
  echo "$(cd "$(dirname "$1")/.."; pwd -P)"
}

server() {
	make stop
	has_changes && npm ci
	make build
	make start &
}

main() {
	cd "$(get_base_path)"
	source '.env'

	if [ "$ENVIRONMENT" != 'production' ]; then
		return '0'
	fi

	server
	browser
}

main
