#!/usr/bin/env bash

clean() {
	echo
	kill $(jobs -pr)
	wait
}

main() {
	trap 'clean' 'SIGINT' 'SIGTERM'

	ssh -L 0.0.0.0:9223:localhost:9222 nostalgia -N &
	open 'http://localhost:9223' &
	wait
}

main
