#!/usr/bin/env bash

main() {
	local pid="$(ps | grep 'server/main.js' | grep -v grep | tr -s ' ' '\t' | cut -f 1)"

	if [ -z "$pid" ]; then
		return 1
	fi

	kill "$pid"

	while ps -p "$pid" &> /dev/null; do
		sleep 0.2
	done

	echo 'yo'
}

main
