#!/usr/bin/env bash

clean() {
	echo
	kill $(jobs -pr)
	wait
}

images() {
	fswatch -0 'client/images' | xargs -0 -n 1 tasks/images
}

main() {
	trap 'clean' 'SIGINT' 'SIGTERM'

	images &
	scripts &
	styles &
	templates &
	start &

	wait
}

restart() {
	tasks/stop
	tasks/start &
}

scripts() {
	while read -d '' event; do
		tasks/scripts
		tasks/templates
	done < <(fswatch -0 'client/scripts')
}

start() {
	restart
	fswatch -0 'server' | xargs -0 -n 1 restart
}

styles() {
	while read -d '' event; do
		tasks/styles
		tasks/templates
	done < <(fswatch -0 'client/styles')
}

templates() {
	fswatch -0 'client/templates' | xargs -0 -n 1 tasks/templates
}

main "$@"
